import 'package:json_annotation/json_annotation.dart';

part 'mission_creation_session.g.dart';

/// Risk level for each mission
enum RiskLevel {
  @JsonValue('low')
  low,
  @JsonValue('medium')
  medium,
  @JsonValue('high')
  high,
}

/// Represents a single mission in the mission map
@JsonSerializable()
class Mission {
  final String mission; // "Mission 1 — Building Local Capacity"
  final String missionSequence; // "1", "2", "3", etc.
  final String focus; // What this mission focuses on
  final String structuralShift; // What structural change occurs
  final String capabilityRequired; // What capabilities need to be developed
  final String riskOrValueGuardrail; // Risk assessment and value constraints
  final String timeHorizon; // "0-2 years", "2-4 years", etc.
  final RiskLevel? riskLevel; // Parsed risk level (low, medium, high)
  final int durationMonths; // Duration of this mission in months (default 12)

  Mission({
    required this.mission,
    required this.missionSequence,
    required this.focus,
    required this.structuralShift,
    required this.capabilityRequired,
    required this.riskOrValueGuardrail,
    required this.timeHorizon,
    this.riskLevel,
    this.durationMonths = 12,
  });

  factory Mission.fromJson(Map<String, dynamic> json) => _$MissionFromJson(json);

  Map<String, dynamic> toJson() => _$MissionToJson(this);

  Mission copyWith({
    String? mission,
    String? missionSequence,
    String? focus,
    String? structuralShift,
    String? capabilityRequired,
    String? riskOrValueGuardrail,
    String? timeHorizon,
    RiskLevel? riskLevel,
    int? durationMonths,
  }) {
    return Mission(
      mission: mission ?? this.mission,
      missionSequence: missionSequence ?? this.missionSequence,
      focus: focus ?? this.focus,
      structuralShift: structuralShift ?? this.structuralShift,
      capabilityRequired: capabilityRequired ?? this.capabilityRequired,
      riskOrValueGuardrail: riskOrValueGuardrail ?? this.riskOrValueGuardrail,
      timeHorizon: timeHorizon ?? this.timeHorizon,
      riskLevel: riskLevel ?? this.riskLevel,
      durationMonths: durationMonths ?? this.durationMonths,
    );
  }
}

/// Represents a session of creating a mission map
@JsonSerializable(explicitToJson: true)
class MissionCreationSession {
  final String id;
  final String userId;
  final DateTime startedAt;
  final DateTime? completedAt;

  // CONTEXT (loaded from user profile)
  final String? purposeStatement;
  final List<String>? coreValues;
  final String? visionStatement;
  final int? visionTimeframeYears; // 5, 10, or 15 years

  // STEP 1: Current Mission State
  final String? currentBuilding; // What are you currently building or leading?
  final String? currentScale; // What scale are you operating at?
  final String? currentAuthority; // What authority do you currently hold?

  // STEP 2: Vision State
  final String? visionInfluenceScale; // What scale of influence?
  final String? visionEnvironment; // What kind of environment?
  final String? visionResponsibility; // What level of responsibility?
  final String? visionMeasurableChange; // What measurable change exists?

  // STEP 3: Constraints
  final List<String>? constraintValues; // Values that cannot be violated
  final String? nonNegotiableCommitments; // Non-negotiable commitments
  final String? riskTolerance; // Risk tolerance level

  // AI RESULTS
  final List<Mission>? missionMap; // 3-5 sequential missions generated by AI
  final int? selectedMissionIndex; // Which mission user is currently focused on

  MissionCreationSession({
    required this.id,
    required this.userId,
    required this.startedAt,
    this.completedAt,
    this.purposeStatement,
    this.coreValues,
    this.visionStatement,
    this.visionTimeframeYears,
    this.currentBuilding,
    this.currentScale,
    this.currentAuthority,
    this.visionInfluenceScale,
    this.visionEnvironment,
    this.visionResponsibility,
    this.visionMeasurableChange,
    this.constraintValues,
    this.nonNegotiableCommitments,
    this.riskTolerance,
    this.missionMap,
    this.selectedMissionIndex,
  });

  factory MissionCreationSession.fromJson(Map<String, dynamic> json) =>
      _$MissionCreationSessionFromJson(json);

  Map<String, dynamic> toJson() => _$MissionCreationSessionToJson(this);

  MissionCreationSession copyWith({
    String? id,
    String? userId,
    DateTime? startedAt,
    DateTime? completedAt,
    String? purposeStatement,
    List<String>? coreValues,
    String? visionStatement,
    int? visionTimeframeYears,
    String? currentBuilding,
    String? currentScale,
    String? currentAuthority,
    String? visionInfluenceScale,
    String? visionEnvironment,
    String? visionResponsibility,
    String? visionMeasurableChange,
    List<String>? constraintValues,
    String? nonNegotiableCommitments,
    String? riskTolerance,
    List<Mission>? missionMap,
    int? selectedMissionIndex,
  }) {
    return MissionCreationSession(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      purposeStatement: purposeStatement ?? this.purposeStatement,
      coreValues: coreValues ?? this.coreValues,
      visionStatement: visionStatement ?? this.visionStatement,
      visionTimeframeYears: visionTimeframeYears ?? this.visionTimeframeYears,
      currentBuilding: currentBuilding ?? this.currentBuilding,
      currentScale: currentScale ?? this.currentScale,
      currentAuthority: currentAuthority ?? this.currentAuthority,
      visionInfluenceScale: visionInfluenceScale ?? this.visionInfluenceScale,
      visionEnvironment: visionEnvironment ?? this.visionEnvironment,
      visionResponsibility: visionResponsibility ?? this.visionResponsibility,
      visionMeasurableChange: visionMeasurableChange ?? this.visionMeasurableChange,
      constraintValues: constraintValues ?? this.constraintValues,
      nonNegotiableCommitments: nonNegotiableCommitments ?? this.nonNegotiableCommitments,
      riskTolerance: riskTolerance ?? this.riskTolerance,
      missionMap: missionMap ?? this.missionMap,
      selectedMissionIndex: selectedMissionIndex ?? this.selectedMissionIndex,
    );
  }
}
