import 'package:json_annotation/json_annotation.dart';

part 'vision_creation_session.g.dart';

/// Represents a vision statement option generated by AI
@JsonSerializable()
class VisionOption {
  final String label; // "Clear & Strategic", "Systems & Institutional", "Meaning & Human Impact"
  final String statement;

  VisionOption({
    required this.label,
    required this.statement,
  });

  factory VisionOption.fromJson(Map<String, dynamic> json) =>
      _$VisionOptionFromJson(json);

  Map<String, dynamic> toJson() => _$VisionOptionToJson(this);
}

/// Represents the scale/domain of influence
enum InfluenceScale {
  @JsonValue('individuals')
  individuals,
  @JsonValue('organizations')
  organizations,
  @JsonValue('institutions')
  institutions,
  @JsonValue('systems')
  systems,
}

/// Represents a session of creating a vision statement
@JsonSerializable(explicitToJson: true)
class VisionCreationSession {
  final String id;
  final String userId;
  final DateTime startedAt;
  final DateTime? completedAt;
  
  // User inputs
  final int? timeframeYears; // 5, 10, or 15
  final String? meaningfulChange; // Response to change question
  final InfluenceScale? influenceScale;
  final String? roleDescription; // What role user plays
  
  // Context from user profile
  final String? purposeStatement; // User's purpose
  final List<String>? coreValues; // User's core values
  
  // AI generated options
  final List<VisionOption>? visionOptions; // 3 options from AI
  final int? selectedOptionIndex; // Which option user selected (0, 1, or 2)
  final String? customStatement; // If user edited the selected option

  VisionCreationSession({
    required this.id,
    required this.userId,
    required this.startedAt,
    this.completedAt,
    this.timeframeYears,
    this.meaningfulChange,
    this.influenceScale,
    this.roleDescription,
    this.purposeStatement,
    this.coreValues,
    this.visionOptions,
    this.selectedOptionIndex,
    this.customStatement,
  });

  factory VisionCreationSession.fromJson(Map<String, dynamic> json) =>
      _$VisionCreationSessionFromJson(json);

  Map<String, dynamic> toJson() => _$VisionCreationSessionToJson(this);

  VisionCreationSession copyWith({
    String? id,
    String? userId,
    DateTime? startedAt,
    DateTime? completedAt,
    int? timeframeYears,
    String? meaningfulChange,
    InfluenceScale? influenceScale,
    String? roleDescription,
    String? purposeStatement,
    List<String>? coreValues,
    List<VisionOption>? visionOptions,
    int? selectedOptionIndex,
    String? customStatement,
  }) {
    return VisionCreationSession(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      timeframeYears: timeframeYears ?? this.timeframeYears,
      meaningfulChange: meaningfulChange ?? this.meaningfulChange,
      influenceScale: influenceScale ?? this.influenceScale,
      roleDescription: roleDescription ?? this.roleDescription,
      purposeStatement: purposeStatement ?? this.purposeStatement,
      coreValues: coreValues ?? this.coreValues,
      visionOptions: visionOptions ?? this.visionOptions,
      selectedOptionIndex: selectedOptionIndex ?? this.selectedOptionIndex,
      customStatement: customStatement ?? this.customStatement,
    );
  }
}
