import 'package:json_annotation/json_annotation.dart';

part 'agent_question.g.dart';

/// Types of questions the agent can ask
enum QuestionType {
  /// Comparing relative importance of two preferences
  @JsonValue('WEIGHT_COMPARISON')
  weightComparison,

  /// Determining monetary value for a preference
  @JsonValue('MONETARY_VALUE')
  monetaryValue,

  /// Evaluating trade-offs between preferences
  @JsonValue('TRADEOFF')
  tradeoff,

  /// General clarification question
  @JsonValue('CLARIFICATION')
  clarification,
}

/// Represents a multiple-choice question generated by the agent
@JsonSerializable()
class AgentQuestion {
  /// Unique identifier for the question
  final String id;

  /// The question text to display to the user
  final String questionText;

  /// List of multiple choice options (typically 3-4 options)
  final List<String> options;

  /// Type of question being asked
  final QuestionType type;

  /// Brief explanation of why this question is being asked
  final String reasoning;

  /// Which preferences this question is about (for tracking)
  final List<String> relatedPreferences;

  /// Expected impact on weights (for internal tracking)
  final Map<String, String>? expectedImpact;

  AgentQuestion({
    required this.id,
    required this.questionText,
    required this.options,
    required this.type,
    this.reasoning = '',
    this.relatedPreferences = const [],
    this.expectedImpact,
  });

  /// Create a copy with updated fields
  AgentQuestion copyWith({
    String? id,
    String? questionText,
    List<String>? options,
    QuestionType? type,
    String? reasoning,
    List<String>? relatedPreferences,
    Map<String, String>? expectedImpact,
  }) {
    return AgentQuestion(
      id: id ?? this.id,
      questionText: questionText ?? this.questionText,
      options: options ?? this.options,
      type: type ?? this.type,
      reasoning: reasoning ?? this.reasoning,
      relatedPreferences: relatedPreferences ?? this.relatedPreferences,
      expectedImpact: expectedImpact ?? this.expectedImpact,
    );
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() => _$AgentQuestionToJson(this);

  /// Create from JSON
  factory AgentQuestion.fromJson(Map<String, dynamic> json) =>
      _$AgentQuestionFromJson(json);

  @override
  String toString() => 'AgentQuestion(id: $id, type: $type, '
      'options: ${options.length})';
}
